title: Evolveum Docs
shortname: Docs
email: docs@evolveum.com
description: >- # this means to ignore newlines until "baseurl:"
  Evolveum public documents and files
fqdn: docs.evolveum.com
baseurl: null # the subpath of your site, e.g. /blog
url: "https://docs.evolveum.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

# Build settings
theme: evolveum-jekyll-theme
plugins:
  - jekyll-feed
  - evolveum-jekyll-plugin

exclude:
  - .idea/

# Ugly temporary solution, watch https://tracker.evolveum.com/projects/infrastructure/work_packages/4424/activity for better resolution.
sass:
  quiet_deps: true
  silence_deprecations:
    - import

asciidoctor:
  attributes:
    xref-ignored-prefixes:
      - /media

defaults:
  - scope:
      path: ""
    values:
      liquid: true
  - scope:
      path: "assets"
    values:
      visibility: "system"
  - scope:
      path: "feed.xml"
    values:
      visibility: "system"

  - scope:
      path: "README"
    values:
      visibility: "system"
  - scope:
      path: "CONTRIBUTING"
    values:
      visibility: "system"

environment:
  searchUrl: search.evolveum.com
  docsUrl: docs.evolveum.com
  name: docs-test
  midpointRepositoryGhName: Evolveum/midpoint
  bookTag: "v2.3"
